# Generated by Django 4.2.1 on 2024-03-20 01:21

import django.db.models.deletion
from django.db import migrations, models


def create_pricing(apps, schema_editor):
    pricing_model = apps.get_model('Plan_Management', 'Pricing')
    pricing_model.objects.create()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("Monthly/Annually", "Monthly Annually"),
                            ("Custom", "Custom"),
                        ],
                        default="Monthly/Annually",
                        max_length=25,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Pause", "Pause")],
                        default="Active",
                        max_length=25,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cents_per_point", models.FloatField(default=0.0)),
                ("points_per_sample", models.IntegerField(default=0)),
                ("points_per_midi", models.IntegerField(default=0)),
                ("points_per_preset", models.IntegerField(default=0)),
                ("non_profits_licence", models.IntegerField(default=0)),
                ("commercial_licence", models.IntegerField(default=0)),
                ("unlimited_licence", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PlanDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pricing", models.IntegerField()),
                ("points", models.IntegerField()),
                (
                    "timeline",
                    models.CharField(
                        choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                        default="Monthly",
                        max_length=25,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("$", "Dollar")], default="$", max_length=1
                    ),
                ),
                ("duration", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="Plan_Management.plan",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_pricing
        ),
    ]
