# Generated by Django 4.2.1 on 2024-05-30 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User_Management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="city",
            new_name="city_or_state",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="country_or_state",
            new_name="country",
        ),
    ]
