# Generated by Django 4.2.1 on 2024-08-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Product_Management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="likes",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="like",
                to="Product_Management.audiofiles",
            ),
        ),
    ]
