# Generated by Django 4.2.1 on 2024-12-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beats_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatfile',
            name='file_extension',
            field=models.CharField(choices=[('mp3', 'Mp3'), ('wav', 'Wav'), ('zip', 'Zip')], default='mp3', max_length=10),
        ),
        migrations.AlterField(
            model_name='beataudiofiles',
            name='beat_type',
            field=models.CharField(choices=[('Sample', 'Sample'), ('MIDI', 'Midi'), ('Preset', 'Preset')], max_length=25),
        ),
        migrations.AlterField(
            model_name='beatfile',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=1000, null=True, upload_to='audio-beat-files/'),
        ),
        migrations.AlterField(
            model_name='beatssubmissions',
            name='beat_type',
            field=models.CharField(choices=[('Sample', 'Sample'), ('MIDI', 'Midi'), ('Preset', 'Preset')], default='Sample', max_length=25),
        ),
    ]
